from pytorch_transformers import DistilBertTokenizer

from transformers import DebertaV2Config, DebertaTokenizer, BertTokenizer, RobertaTokenizer, DistilBertConfig, BertConfig, \
    RobertaConfig

from .processors import ConllNerProcessor, GedProcessor, JNLNerProcessor, BC2NerProcessor, SimplifiedNerProcessor, \
    BC4NerProcessor, MNLIProcessor, HANSProcessor, MNISTProcessor, CIFAR10Processor, CIFAR100Processor, WNUT17NerProcessor
from .metrics import get_ner_metrics, get_ged_metrics, get_ir_metrics, get_wnut_metrics

from .bert_models import BertTokenClassifier, RobertaTokenClassifier, DebertaTokenClassifier


def get_processors():
    return {
            "conll03":                   ConllNerProcessor,
            "conll03-25loc-1":           ConllNerProcessor,
            "conll03-25loc-2":           ConllNerProcessor,
            "conll03-25loc-3":           ConllNerProcessor,
            "conll03-25loc-1-binary":    GedProcessor,
            "conll03-25loc-2-binary":    GedProcessor,
            "conll03-25loc-3-binary":    GedProcessor,
            "conll03-50loc-1":           ConllNerProcessor,
            "conll03-50loc-2":           ConllNerProcessor,
            "conll03-50loc-3":           ConllNerProcessor,
            "conll03-25misc-1":          ConllNerProcessor,
            "conll03-25misc-2":          ConllNerProcessor,
            "conll03-25misc-3":          ConllNerProcessor,
            "conll03-25misc-1-binary":   GedProcessor,
            "conll03-25misc-2-binary":   GedProcessor,
            "conll03-25misc-3-binary":   GedProcessor,
            "conll03-50misc-1":          ConllNerProcessor,
            "conll03-50misc-2":          ConllNerProcessor,
            "conll03-50misc-3":          ConllNerProcessor,
            "conll03-simp":              GedProcessor,

            "conll03-5misc":             ConllNerProcessor,
            "conll03-5loc":              ConllNerProcessor,
            "conll03-15misc":            ConllNerProcessor,
            "conll03-15loc":             ConllNerProcessor,
            "conll03-25misc":            ConllNerProcessor,
            "conll03-25loc":             ConllNerProcessor,
            "conll03-35misc":            ConllNerProcessor,
            "conll03-35loc":             ConllNerProcessor,
            "conll03-45misc":            ConllNerProcessor,
            "conll03-45loc":             ConllNerProcessor,
            "conll03-55misc":            ConllNerProcessor,
            "conll03-55loc":             ConllNerProcessor,
            "conll03-65misc":            ConllNerProcessor,
            "conll03-65loc":             ConllNerProcessor,
            "conll03-75misc":            ConllNerProcessor,
            "conll03-75loc":             ConllNerProcessor,
            "conll03-85misc":            ConllNerProcessor,
            "conll03-85loc":             ConllNerProcessor,
            "conll03-95misc":            ConllNerProcessor,
            "conll03-95loc":             ConllNerProcessor,
            "conll03-105misc":           ConllNerProcessor,
            "conll03-105loc":            ConllNerProcessor,
            "conll03-115misc":           ConllNerProcessor,
            "conll03-115loc":            ConllNerProcessor,
            "conll03-125misc":           ConllNerProcessor,
            "conll03-125loc":            ConllNerProcessor,
            "conll03-135misc":           ConllNerProcessor,
            "conll03-135loc":            ConllNerProcessor,
            "conll03-145misc":           ConllNerProcessor,
            "conll03-145loc":            ConllNerProcessor,
            "conll03-155misc":           ConllNerProcessor,
            "conll03-155loc":            ConllNerProcessor,
            "conll03-165misc":           ConllNerProcessor,
            "conll03-165loc":            ConllNerProcessor,
            "conll03-175misc":           ConllNerProcessor,
            "conll03-175loc":            ConllNerProcessor,
            "conll03-185misc":           ConllNerProcessor,
            "conll03-185loc":            ConllNerProcessor,
            "conll03-195misc":           ConllNerProcessor,
            "conll03-195loc":            ConllNerProcessor,
            "conll03-200misc":           ConllNerProcessor,
            "conll03-200loc":            ConllNerProcessor,
            "conll03-500misc":           ConllNerProcessor,
            "conll03-500loc":            ConllNerProcessor,
            "conll03-1000misc":          ConllNerProcessor,
            "conll03-1000loc":           ConllNerProcessor,

            "fce":                       GedProcessor,
            "w&i":                       GedProcessor,

            "jnlpba":                    JNLNerProcessor,
            "jnlpba-binary":             GedProcessor,
            "jnlpba-simp":               SimplifiedNerProcessor,
            "jnlpba-5cell_line":         JNLNerProcessor,
            "jnlpba-5cell_type":         JNLNerProcessor,
            "jnlpba-5rna":               JNLNerProcessor,
            "jnlpba-10cell_line":        JNLNerProcessor,
            "jnlpba-10cell_type":        JNLNerProcessor,
            "jnlpba-10dna":              JNLNerProcessor,
            "jnlpba-10protein":          JNLNerProcessor,
            "jnlpba-10rna":              JNLNerProcessor,
            "jnlpba-25cell_line":        JNLNerProcessor,
            "jnlpba-25cell_type":        JNLNerProcessor,
            "jnlpba-25dna-1":            JNLNerProcessor,
            "jnlpba-25dna-2":            JNLNerProcessor,
            "jnlpba-25dna-3":            JNLNerProcessor,
            "jnlpba-25dna-binary":       GedProcessor,
            "jnlpba-25dna-1-binary":     GedProcessor,
            "jnlpba-25dna-2-binary":     GedProcessor,
            "jnlpba-25dna-3-binary":     GedProcessor,
            "jnlpba-25protein-1":        JNLNerProcessor,
            "jnlpba-25protein-2":        JNLNerProcessor,
            "jnlpba-25protein-3":        JNLNerProcessor,
            "jnlpba-25protein-binary":   GedProcessor,
            "jnlpba-25protein-1-binary": GedProcessor,
            "jnlpba-25protein-2-binary": GedProcessor,
            "jnlpba-25protein-3-binary": GedProcessor,
            "jnlpba-25rna":              JNLNerProcessor,
            "jnlpba-50cell_line":        JNLNerProcessor,
            "jnlpba-50cell_type":        JNLNerProcessor,
            "jnlpba-50dna":              JNLNerProcessor,
            "jnlpba-50protein":          JNLNerProcessor,
            "jnlpba-50rna":              JNLNerProcessor,
            "jnlpba-100cell_line":       JNLNerProcessor,
            "jnlpba-100cell_type":       JNLNerProcessor,
            "jnlpba-100dna":             JNLNerProcessor,
            "jnlpba-100protein":         JNLNerProcessor,
            "jnlpba-100rna":             JNLNerProcessor,
            "jnlpba-1000cell_line":      JNLNerProcessor,
            "jnlpba-1000cell_type":      JNLNerProcessor,

            "jnlpba-5dna":               JNLNerProcessor,
            "jnlpba-5protein":           JNLNerProcessor,
            "jnlpba-15dna":              JNLNerProcessor,
            "jnlpba-15protein":          JNLNerProcessor,
            "jnlpba-25dna":              JNLNerProcessor,
            "jnlpba-25protein":          JNLNerProcessor,
            "jnlpba-35dna":              JNLNerProcessor,
            "jnlpba-35protein":          JNLNerProcessor,
            "jnlpba-45dna":              JNLNerProcessor,
            "jnlpba-45protein":          JNLNerProcessor,
            "jnlpba-55dna":              JNLNerProcessor,
            "jnlpba-55protein":          JNLNerProcessor,
            "jnlpba-65dna":              JNLNerProcessor,
            "jnlpba-65protein":          JNLNerProcessor,
            "jnlpba-75dna":              JNLNerProcessor,
            "jnlpba-75protein":          JNLNerProcessor,
            "jnlpba-85dna":              JNLNerProcessor,
            "jnlpba-85protein":          JNLNerProcessor,
            "jnlpba-95dna":              JNLNerProcessor,
            "jnlpba-95protein":          JNLNerProcessor,
            "jnlpba-105dna":             JNLNerProcessor,
            "jnlpba-105protein":         JNLNerProcessor,
            "jnlpba-115dna":             JNLNerProcessor,
            "jnlpba-115protein":         JNLNerProcessor,
            "jnlpba-125dna":             JNLNerProcessor,
            "jnlpba-125protein":         JNLNerProcessor,
            "jnlpba-135dna":             JNLNerProcessor,
            "jnlpba-135protein":         JNLNerProcessor,
            "jnlpba-145dna":             JNLNerProcessor,
            "jnlpba-145protein":         JNLNerProcessor,
            "jnlpba-155dna":             JNLNerProcessor,
            "jnlpba-155protein":         JNLNerProcessor,
            "jnlpba-165dna":             JNLNerProcessor,
            "jnlpba-165protein":         JNLNerProcessor,
            "jnlpba-175dna":             JNLNerProcessor,
            "jnlpba-175protein":         JNLNerProcessor,
            "jnlpba-185dna":             JNLNerProcessor,
            "jnlpba-185protein":         JNLNerProcessor,
            "jnlpba-195dna":             JNLNerProcessor,
            "jnlpba-195protein":         JNLNerProcessor,
            "jnlpba-200dna":             JNLNerProcessor,
            "jnlpba-200protein":         JNLNerProcessor,
            "jnlpba-500dna":             JNLNerProcessor,
            "jnlpba-500protein":         JNLNerProcessor,
            "jnlpba-1000dna":            JNLNerProcessor,
            "jnlpba-1000protein":        JNLNerProcessor,

            "bc2gm":                     BC2NerProcessor,
            "bc2gm-simp":                SimplifiedNerProcessor,

            "bc4chemd":                  BC4NerProcessor,
            "bc4chemd-simp":             SimplifiedNerProcessor,

            "mnli":                      MNLIProcessor,
            "hans":                      HANSProcessor,

            "wnut17":                    WNUT17NerProcessor,

            "mnist":                     MNISTProcessor,
            "mnist-1shot":               MNISTProcessor,

            "cifar10":                   CIFAR10Processor,
            "cifar10-1shot":             CIFAR10Processor,

            "cifar100":                  CIFAR100Processor,
            "cifar100-1shot":            CIFAR100Processor
    }


def get_data_dirs_cardinal():
    return {
            "conll03":                   "<data_path>/conll03_ner/ner/full",
            "conll03-25loc-1":           "<data_path>/conll03_ner/ner/25LOC_1",
            "conll03-25loc-2":           "<data_path>/conll03_ner/ner/25LOC_2",
            "conll03-25loc-3":           "<data_path>/conll03_ner/ner/25LOC_3",
            "conll03-25loc-1-binary":    "<data_path>/conll03_ner/ner/25LOC_binary_1",
            "conll03-25loc-2-binary":    "<data_path>/conll03_ner/ner/25LOC_binary_2",
            "conll03-25loc-3-binary":    "<data_path>/conll03_ner/ner/25LOC_binary_3",
            "conll03-50loc-1":           "<data_path>/conll03_ner/ner/50LOC_1",
            "conll03-50loc-2":           "<data_path>/conll03_ner/ner/50LOC_2",
            "conll03-50loc-3":           "<data_path>/conll03_ner/ner/50LOC_3",
            "conll03-25misc-1":          "<data_path>/conll03_ner/ner/25MISC_1",
            "conll03-25misc-2":          "<data_path>/conll03_ner/ner/25MISC_2",
            "conll03-25misc-3":          "<data_path>/conll03_ner/ner/25MISC_3",
            "conll03-25misc-1-binary":   "<data_path>/conll03_ner/ner/25MISC_binary_1",
            "conll03-25misc-2-binary":   "<data_path>/conll03_ner/ner/25MISC_binary_2",
            "conll03-25misc-3-binary":   "<data_path>/conll03_ner/ner/25MISC_binary_3",
            "conll03-50misc-1":          "<data_path>/conll03_ner/ner/50MISC_1",
            "conll03-50misc-2":          "<data_path>/conll03_ner/ner/50MISC_2",
            "conll03-50misc-3":          "<data_path>/conll03_ner/ner/50MISC_3",
            "conll03-simp":              "<data_path>/conll03_ner/tsv",

            "conll03-5misc":             "<data_path>/conll03_ner/ner/5MISC",
            "conll03-5loc":              "<data_path>/conll03_ner/ner/5LOC",
            "conll03-15misc":            "<data_path>/conll03_ner/ner/15MISC",
            "conll03-15loc":             "<data_path>/conll03_ner/ner/15LOC",
            "conll03-25misc":            "<data_path>/conll03_ner/ner/25MISC",
            "conll03-25loc":             "<data_path>/conll03_ner/ner/25LOC",
            "conll03-35misc":            "<data_path>/conll03_ner/ner/35MISC",
            "conll03-35loc":             "<data_path>/conll03_ner/ner/35LOC",
            "conll03-45misc":            "<data_path>/conll03_ner/ner/45MISC",
            "conll03-45loc":             "<data_path>/conll03_ner/ner/45LOC",
            "conll03-55misc":            "<data_path>/conll03_ner/ner/55MISC",
            "conll03-55loc":             "<data_path>/conll03_ner/ner/55LOC",
            "conll03-65misc":            "<data_path>/conll03_ner/ner/65MISC",
            "conll03-65loc":             "<data_path>/conll03_ner/ner/65LOC",
            "conll03-75misc":            "<data_path>/conll03_ner/ner/75MISC",
            "conll03-75loc":             "<data_path>/conll03_ner/ner/75LOC",
            "conll03-85misc":            "<data_path>/conll03_ner/ner/85MISC",
            "conll03-85loc":             "<data_path>/conll03_ner/ner/85LOC",
            "conll03-95misc":            "<data_path>/conll03_ner/ner/95MISC",
            "conll03-95loc":             "<data_path>/conll03_ner/ner/95LOC",
            "conll03-105misc":           "<data_path>/conll03_ner/ner/105MISC",
            "conll03-105loc":            "<data_path>/conll03_ner/ner/105LOC",
            "conll03-115misc":           "<data_path>/conll03_ner/ner/115MISC",
            "conll03-115loc":            "<data_path>/conll03_ner/ner/115LOC",
            "conll03-125misc":           "<data_path>/conll03_ner/ner/125MISC",
            "conll03-125loc":            "<data_path>/conll03_ner/ner/125LOC",
            "conll03-135misc":           "<data_path>/conll03_ner/ner/135MISC",
            "conll03-135loc":            "<data_path>/conll03_ner/ner/135LOC",
            "conll03-145misc":           "<data_path>/conll03_ner/ner/145MISC",
            "conll03-145loc":            "<data_path>/conll03_ner/ner/145LOC",
            "conll03-155misc":           "<data_path>/conll03_ner/ner/155MISC",
            "conll03-155loc":            "<data_path>/conll03_ner/ner/155LOC",
            "conll03-165misc":           "<data_path>/conll03_ner/ner/165MISC",
            "conll03-165loc":            "<data_path>/conll03_ner/ner/165LOC",
            "conll03-175misc":           "<data_path>/conll03_ner/ner/175MISC",
            "conll03-175loc":            "<data_path>/conll03_ner/ner/175LOC",
            "conll03-185misc":           "<data_path>/conll03_ner/ner/185MISC",
            "conll03-185loc":            "<data_path>/conll03_ner/ner/185LOC",
            "conll03-195misc":           "<data_path>/conll03_ner/ner/195MISC",
            "conll03-195loc":            "<data_path>/conll03_ner/ner/195LOC",
            "conll03-200misc":           "<data_path>/conll03_ner/ner/200MISC",
            "conll03-200loc":            "<data_path>/conll03_ner/ner/200LOC",
            "conll03-500misc":           "<data_path>/conll03_ner/ner/500MISC",
            "conll03-500loc":            "<data_path>/conll03_ner/ner/500LOC",
            "conll03-1000misc":          "<data_path>/conll03_ner/ner/1000MISC",
            "conll03-1000loc":           "<data_path>/conll03_ner/ner/1000LOC",

            "fce":                       "<data_path>/fce/tsv",
            "w&i":                       "<data_path>/wi+locness/tsv",

            "jnlpba":                    "<data_path>/JNLPBA/full",
            "jnlpba-binary":             "<data_path>/JNLPBA/full_binary",
            "jnlpba-simp":               "<data_path>/JNLPBA/simp",
            "jnlpba-5cell_line":         "<data_path>/JNLPBA/5cell_line",
            "jnlpba-5cell_type":         "<data_path>/JNLPBA/5cell_type",
            "jnlpba-5rna":               "<data_path>/JNLPBA/5RNA",
            "jnlpba-10cell_line":        "<data_path>/JNLPBA/10cell_line",
            "jnlpba-10cell_type":        "<data_path>/JNLPBA/10cell_type",
            "jnlpba-10dna":              "<data_path>/JNLPBA/10DNA",
            "jnlpba-10protein":          "<data_path>/JNLPBA/10protein",
            "jnlpba-10rna":              "<data_path>/JNLPBA/10RNA",
            "jnlpba-25cell_line":        "<data_path>/JNLPBA/25cell_line",
            "jnlpba-25cell_type":        "<data_path>/JNLPBA/25cell_type",
            "jnlpba-25dna-1":            "<data_path>/JNLPBA/25DNA_1",
            "jnlpba-25dna-2":            "<data_path>/JNLPBA/25DNA_2",
            "jnlpba-25dna-3":            "<data_path>/JNLPBA/25DNA_3",
            "jnlpba-25dna-binary":       "<data_path>/JNLPBA/25dna_binary",
            "jnlpba-25dna-1-binary":     "<data_path>/JNLPBA/25DNA_binary_1",
            "jnlpba-25dna-2-binary":     "<data_path>/JNLPBA/25DNA_binary_2",
            "jnlpba-25dna-3-binary":     "<data_path>/JNLPBA/25DNA_binary_3",
            "jnlpba-25protein-1":        "<data_path>/JNLPBA/25protein",
            "jnlpba-25protein-2":        "<data_path>/JNLPBA/25protein_1",
            "jnlpba-25protein-3":        "<data_path>/JNLPBA/25protein_2",
            "jnlpba-25protein-binary":   "<data_path>/JNLPBA/25protein_binary",
            "jnlpba-25protein-1-binary": "<data_path>/JNLPBA/25protein_binary_1",
            "jnlpba-25protein-2-binary": "<data_path>/JNLPBA/25protein_binary_2",
            "jnlpba-25protein-3-binary": "<data_path>/JNLPBA/25protein_binary_3",
            "jnlpba-25rna":              "<data_path>/JNLPBA/25RNA",
            "jnlpba-50cell_line":        "<data_path>/JNLPBA/50cell_line",
            "jnlpba-50cell_type":        "<data_path>/JNLPBA/50cell_type",
            "jnlpba-50dna":              "<data_path>/JNLPBA/50DNA",
            "jnlpba-50protein":          "<data_path>/JNLPBA/50protein",
            "jnlpba-50rna":              "<data_path>/JNLPBA/50RNA",
            "jnlpba-100cell_line":       "<data_path>/JNLPBA/100cell_line",
            "jnlpba-100cell_type":       "<data_path>/JNLPBA/100cell_type",
            "jnlpba-100dna":             "<data_path>/JNLPBA/100DNA",
            "jnlpba-100protein":         "<data_path>/JNLPBA/100protein",
            "jnlpba-100rna":             "<data_path>/JNLPBA/100RNA",
            "jnlpba-1000cell_line":      "<data_path>/JNLPBA/1000cell_line",
            "jnlpba-1000cell_type":      "<data_path>/JNLPBA/1000cell_type",

            "jnlpba-5dna":               "<data_path>/JNLPBA/5DNA",
            "jnlpba-5protein":           "<data_path>/JNLPBA/5protein",
            "jnlpba-15dna":              "<data_path>/JNLPBA/15DNA",
            "jnlpba-15protein":          "<data_path>/JNLPBA/15protein",
            "jnlpba-25dna":              "<data_path>/JNLPBA/25DNA",
            "jnlpba-25protein":          "<data_path>/JNLPBA/25protein",
            "jnlpba-35dna":              "<data_path>/JNLPBA/35DNA",
            "jnlpba-35protein":          "<data_path>/JNLPBA/35protein",
            "jnlpba-45dna":              "<data_path>/JNLPBA/45DNA",
            "jnlpba-45protein":          "<data_path>/JNLPBA/45protein",
            "jnlpba-55dna":              "<data_path>/JNLPBA/55DNA",
            "jnlpba-55protein":          "<data_path>/JNLPBA/55protein",
            "jnlpba-65dna":              "<data_path>/JNLPBA/65DNA",
            "jnlpba-65protein":          "<data_path>/JNLPBA/65protein",
            "jnlpba-75dna":              "<data_path>/JNLPBA/75DNA",
            "jnlpba-75protein":          "<data_path>/JNLPBA/75protein",
            "jnlpba-85dna":              "<data_path>/JNLPBA/85DNA",
            "jnlpba-85protein":          "<data_path>/JNLPBA/85protein",
            "jnlpba-95dna":              "<data_path>/JNLPBA/95DNA",
            "jnlpba-95protein":          "<data_path>/JNLPBA/95protein",
            "jnlpba-105dna":             "<data_path>/JNLPBA/105DNA",
            "jnlpba-105protein":         "<data_path>/JNLPBA/105protein",
            "jnlpba-115dna":             "<data_path>/JNLPBA/115DNA",
            "jnlpba-115protein":         "<data_path>/JNLPBA/115protein",
            "jnlpba-125dna":             "<data_path>/JNLPBA/125DNA",
            "jnlpba-125protein":         "<data_path>/JNLPBA/125protein",
            "jnlpba-135dna":             "<data_path>/JNLPBA/135DNA",
            "jnlpba-135protein":         "<data_path>/JNLPBA/135protein",
            "jnlpba-145dna":             "<data_path>/JNLPBA/145DNA",
            "jnlpba-145protein":         "<data_path>/JNLPBA/145protein",
            "jnlpba-155dna":             "<data_path>/JNLPBA/155DNA",
            "jnlpba-155protein":         "<data_path>/JNLPBA/155protein",
            "jnlpba-165dna":             "<data_path>/JNLPBA/165DNA",
            "jnlpba-165protein":         "<data_path>/JNLPBA/165protein",
            "jnlpba-175dna":             "<data_path>/JNLPBA/175DNA",
            "jnlpba-175protein":         "<data_path>/JNLPBA/175protein",
            "jnlpba-185dna":             "<data_path>/JNLPBA/185DNA",
            "jnlpba-185protein":         "<data_path>/JNLPBA/185protein",
            "jnlpba-195dna":             "<data_path>/JNLPBA/195DNA",
            "jnlpba-195protein":         "<data_path>/JNLPBA/195protein",
            "jnlpba-200dna":             "<data_path>/JNLPBA/200DNA",
            "jnlpba-200protein":         "<data_path>/JNLPBA/200protein",
            "jnlpba-500dna":             "<data_path>/JNLPBA/500DNA",
            "jnlpba-500protein":         "<data_path>/JNLPBA/500protein",
            "jnlpba-1000dna":            "<data_path>/JNLPBA/1000DNA",
            "jnlpba-1000protein":        "<data_path>/JNLPBA/1000protein",

            "bc2gm":                     "<data_path>/BC2GM/full",
            "bc2gm-simp":                "<data_path>/BC2GM/simp",

            "bc4chemd":                  "<data_path>/BC4CHEMD/full",
            "bc4chemd-simp":             "<data_path>/BC4CHEMD/simp",

            "mnli":                      "<data_path>/MNLI",
            "hans":                      "<data_path>/HANS",

            "wnut17": "<data_path>/WNUT17/full",

            "mnist":                     None,
            "mnist-1shot":               None,

            "cifar10":                   None,
            "cifar10-1shot":             None,

            "cifar100":                  None,
            "cifar100-1shot":            None
    }


def get_models():
    return {
            "BERT":          BertTokenClassifier,
            "BIOBERT":       BertTokenClassifier,
            "ROBERTA":       RobertaTokenClassifier,
            "DEBERTA":       DebertaTokenClassifier,

    }


def get_reporters():
    return {
            "ner": get_ner_metrics,
            "ged": get_ged_metrics,
            "nli": get_ir_metrics,
            "ir":  get_ir_metrics,
            "wnut": get_wnut_metrics
    }


def get_memories():
    return {
            "none": None,
    }


def get_tokenizers():
    return {
            "DISTILBERT":    DistilBertTokenizer,
            "BERT":          BertTokenizer,
            "BIOBERT":       BertTokenizer,
            "ROBERTA":       RobertaTokenizer,
            "DEBERTA":       DebertaTokenizer,

    }


def get_configs():
    return {
            "DISTILBERT":    DistilBertConfig,
            "BERT":          BertConfig,
            "BIOBERT":       BertConfig,
            "ROBERTA":       RobertaConfig,
            "DEBERTA":       DebertaV2Config,

    }


def get_base_parameters_trainer():
    return dict(
            wandb=True,
            data_dir=None,
            model_name="bert-base-cased",
            task_name="ged",
            dataset_name="fce",
            output_dir="./out/",
            cache_dir="",
            max_seq_length=50,
            do_train=True,
            do_eval=True,
            eval_on="dev",
            do_lower_case=False,
            train_batch_size=64,
            eval_batch_size=64,
            learning_rate=1e-4,
            num_train_epochs=4.0,
            warmup_proportion=0.1,
            weight_decay=0.01,
            adam_epsilon=1e-8,
            max_grad_norm=1.0,
            no_cuda=False,
            local_rank=-1,
            seed=106,
            gradient_accumulation_steps=1,
            fp16=False,
            fp16_opt_level="O1",
            loss_scale=0,
            server_ip="",
            server_port="",
            print_every=25,
            n_gpu=1,
            noise_addition=0.0
    )
